- name: Create the blackbox user
  become: True
  user:
    name: "{{ blackbox_user }}"
    system: yes
    state: present

- name: "Ensure {{ blackbox_dir }} exists"
  become: True
  file:
    dest: "{{ blackbox_dir }}"
    owner: "{{ blackbox_user }}"
    group: "{{ blackbox_user }}"
    state: directory

- name: Download blackbox_exporter
  become: True
  get_url:
    checksum: "{{ blackbox_checksum }}"
    url: "{{ blackbox_url }}"
    dest: "/tmp/blackbox_exporter.tar.gz"
  register: blackbox_download

- name: Untar the blackbox archive
  become: True
  unarchive:
    src: "/tmp//blackbox_exporter.tar.gz"
    dest: "{{ blackbox_dir }}"
    owner: "{{ blackbox_user }}"
    group: "{{ blackbox_user }}"
    mode: 0744
    remote_src: True
    extra_opts: "--strip-components=1"
  when: blackbox_download is changed
  notify: restart blackbox_exporter

- name: Configure systemd service
  become: True
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
  notify: restart blackbox_exporter

- name: Enable and start the blackbox_exporter service
  become: True
  systemd:
    daemon_reload: yes
    name: blackbox_exporter.service
    enabled: yes
    state: started
