- name: Create the blackbox user
  become: true
  ansible.builtin.user:
    name: "{{ blackbox_user }}"
    system: true
    state: present

- name: "Ensure {{ blackbox_dir }} exists"
  become: true
  ansible.builtin.file:
    dest: "{{ blackbox_dir }}"
    owner: "{{ blackbox_user }}"
    group: "{{ blackbox_user }}"
    state: directory
    mode: 0744

- name: Download blackbox_exporter
  become: true
  ansible.builtin.get_url:
    checksum: "{{ blackbox_checksum }}"
    url: "{{ blackbox_url }}"
    dest: "/tmp/blackbox_exporter.tar.gz"
    mode: 0744
  register: blackbox_download

- name: Untar the blackbox archive
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/blackbox_exporter.tar.gz"
    dest: "{{ blackbox_dir }}"
    owner: "{{ blackbox_user }}"
    group: "{{ blackbox_user }}"
    mode: 0744
    remote_src: true
    extra_opts: "--strip-components=1"
  when: blackbox_download is changed
  notify: restart blackbox_exporter

- name: Configure systemd service
  become: true
  ansible.builtin.template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    mode: 0644
  notify: restart blackbox_exporter

- name: Enable and start the blackbox_exporter service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: blackbox_exporter.service
    enabled: true
    state: started
